stages:
  prepare:
    cmd: python mydataset/prepare.py
    params:
      - data
    deps:
      - mydataset/FPS1024/
      - mydataset/prepare.py

  train:
    cmd: python train.py
    params:
      - data
      - train
    deps:
      - mydataset/small_train/
      - mydataset/small_val/
      - mydataset/small_test/
    outs:
      - logs/small
  visualize:
    cmd: python -m tensorboard.main --logdir logs --port=3111 --host=127.0.0.1
    deps:
      - logs/
# TODO: validate
