stages:
  prepare:
    cmd: python mydataset/prepare.py
    params:
      - data
    deps:
      - mydataset/FPS1024/
      - mydataset/prepare.py
    # outs:
    #   - mydataset/my_train/
    #   - mydataset/my_val/
    #   - mydataset/my_test/

  train:
    cmd: python train.py
    deps:
      - mydataset/my_train/
      - mydataset/my_val/
      - mydataset/my_test/
    outs:
      - logs/
# TODO: visualize-point-cloud
# TODO: validate
